version: "3.1"

services:
  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./wordpress:/var/www/html
      - ./dev-nginx-conf:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
    networks:
      - app-network
