version: "3.1"

services:
  wordpress:
    depends_on:
      - mysql
    image: wordpress:5.7.1-fpm-alpine
    container_name: $WORDPRESS_CONTAINER_NAME
    restart: unless-stopped
    env_file: .env
    environment:
      WORDPRESS_DB_PASSWORD: $MYSQL_ROOT_PASSWORD
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_NAME: $MYSQL_DATABASE
    volumes:
      - ./wordpress:/var/www/html
    networks:
      - app-network

  mysql:
    container_name: $MYSQL_CONTAINER_NAME
    restart: unless-stopped
    image: mysql:8
    volumes:
      - ./database:/home/database/
    environment:
      MYSQL_DATABASE: $MYSQL_DATABASE
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    networks:
      - app-network

  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: webserver
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./wordpress:/var/www/html
      - ./nginx-conf:/etc/nginx/conf.d
      - ./certs:/etc/letsencrypt
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
